### ISSUE TITLE
移动端适配，右侧列表无法关闭

### ISSUE THREAD

**Issue by chance-do** [mjyi/Gemini#1]
如题，大神赶紧更新

**Comment by roninro** [comment]
@do-chieh 可以的。点击其他地方就好了。

**Comment by chance-do** [comment]
这里可不可以调成，点击x也能关闭啊

2017年6月22日 +0800 17:41 浅浅浅 <notifications@github.com>，写道：

@do-chieh<https://github.com/do-chieh> 可以的。点击其他地方就好了。
